#!/usr/bin/bash

if [[ ! -x "${SDK}/usr/bin/dotnet" ]]; then
  workshopctl set-health --code="dotnet-not-installed" error ".NET SDK not installed."
  exit 0
fi

if ! sudo -u workshop --login dotnet --info >/dev/null 2>&1; then
  workshopctl set-health --code="dotnet-not-on-path" error ".NET SDK not available on the \$PATH."
  exit 0
fi

workshopctl set-health okay
