#!/usr/bin/bash

# NOTE: we use apt-get instead of apt for non-interactive package installation.
# apt will prompt services restart for some of the packages below which will
# make the SDK installation stall forever.

apt-get -y update
# Install libicu package needed for .NET globalization features.
apt-get -y install libicu-dev
